# Generated by Django 4.0.3 on 2023-07-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(default='created', max_length=20)),
                ('vin', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='automobile',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salesperson',
        ),
        migrations.RenameModel(
            old_name='Salesperson',
            new_name='Technician',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='service_rest.technician'),
        ),
    ]
